name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        emacs_version:
          - 24.3
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - snapshot
        include:
          - emacs_version: 24.3
            ignore_popup: 1
          - emacs_version: 24.4
            ignore_popup: 1
          - emacs_version: 24.5
            ignore_popup: 1
    env:
      EMACS_LINT_IGNORE: ${{ matrix.lint_ignore }}
      LANGTOOL_POPUP_IGNORE: ${{ matrix.ignore_popup }}
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v3
    - name: Run tests
      run: './run-ci.sh'
